/**
 * 25 rehab / demo hand gestures — ids match ghost_hand.POSES and public/poses/*.png names.
 */
export const GESTURE_LIST = [
  { id: 'open_hand', label: 'Open Hand', icon: '🖐️' },
  { id: 'fist', label: 'Fist', icon: '✊' },
  { id: 'point', label: 'Point', icon: '☝️' },
  { id: 'thumbs_up', label: 'Thumbs Up', icon: '👍' },
  { id: 'peace_sign', label: 'Peace', icon: '✌️' },
  { id: 'ok_sign', label: 'OK Sign', icon: '👌' },
  { id: 'pinch', label: 'Pinch', icon: '🤏' },
  { id: 'flat_hand', label: 'Flat Hand', icon: '🖐️' },
  { id: 'shaka', label: 'Shaka', icon: '🤙' },
  { id: 'rock_on', label: 'Rock On', icon: '🤘' },
  { id: 'stop_hand', label: 'Stop', icon: '✋' },
  { id: 'claw', label: 'Claw', icon: '🦀' },
  { id: 'pinch_wide', label: 'Wide Pinch', icon: '↔️' },
  { id: 'tripod_grasp', label: 'Tripod Grasp', icon: '🔻' },
  { id: 'lateral_pinch', label: 'Lateral Pinch', icon: '↔️' },
  { id: 'number_one', label: 'One', icon: '1️⃣' },
  { id: 'number_two', label: 'Two', icon: '2️⃣' },
  { id: 'number_three', label: 'Three', icon: '3️⃣' },
  { id: 'number_four', label: 'Four', icon: '4️⃣' },
  { id: 'number_five', label: 'Five', icon: '5️⃣' },
  { id: 'relaxed_spread', label: 'Relaxed Spread', icon: '🖖' },
  { id: 'half_fist', label: 'Half Fist', icon: '✊' },
  { id: 'index_only', label: 'Index Only', icon: '☝️' },
  { id: 'thumb_out', label: 'Thumb Out', icon: '👍' },
  { id: 'spread_wide', label: 'Spread Wide', icon: '🖐️' },
  // Arm exercises (for neuroplasticity based on brain scan)
  { id: 'arm_raise', label: 'Arm Raise', icon: '💪' },
  { id: 'elbow_flex', label: 'Elbow Flex', icon: '🦾' },
  { id: 'shoulder_abduct', label: 'Shoulder Lift', icon: '🙌' },
  { id: 'wrist_circle', label: 'Wrist Circle', icon: '🔄' },
] as const

export type Gesture = (typeof GESTURE_LIST)[number]['id']

/** Arm exercise IDs — shown with arm skeleton, not hand skeleton. */
export const ARM_EXERCISE_IDS: Gesture[] = ['arm_raise', 'elbow_flex', 'shoulder_abduct', 'wrist_circle']

export const GESTURE_IDS: Gesture[] = GESTURE_LIST.map(g => g.id)

/** Which SVG skeleton template to show (3 primitives). */
export const SKELETON_TEMPLATE: Record<Gesture, 'open_hand' | 'fist' | 'point' | 'arm'> = {
  open_hand: 'open_hand',
  fist: 'fist',
  point: 'point',
  thumbs_up: 'point',
  peace_sign: 'open_hand',
  ok_sign: 'fist',
  pinch: 'fist',
  flat_hand: 'open_hand',
  shaka: 'open_hand',
  rock_on: 'open_hand',
  stop_hand: 'open_hand',
  claw: 'fist',
  pinch_wide: 'fist',
  tripod_grasp: 'fist',
  lateral_pinch: 'fist',
  number_one: 'point',
  number_two: 'open_hand',
  number_three: 'open_hand',
  number_four: 'open_hand',
  number_five: 'open_hand',
  relaxed_spread: 'open_hand',
  half_fist: 'fist',
  index_only: 'point',
  thumb_out: 'point',
  spread_wide: 'open_hand',
  arm_raise: 'arm',
  elbow_flex: 'arm',
  shoulder_abduct: 'arm',
  wrist_circle: 'arm',
}

export const GESTURE_MESSAGES: Record<Gesture, string> = {
  open_hand: 'Open your hand wide!',
  fist: 'Make a tight fist!',
  point: 'Point your index finger!',
  thumbs_up: 'Thumbs up!',
  peace_sign: 'Peace — two fingers up!',
  ok_sign: 'Make an OK circle with thumb and index!',
  pinch: 'Pinch thumb and index together!',
  flat_hand: 'Keep fingers together, palm flat!',
  shaka: 'Hang loose — thumb and pinky out!',
  rock_on: 'Rock on — horns up!',
  stop_hand: 'Palm forward like stop!',
  claw: 'Claw shape — fingers bent!',
  pinch_wide: 'Wide pinch — tips close!',
  tripod_grasp: 'Tripod — thumb, index, middle!',
  lateral_pinch: 'Pinch from the side!',
  number_one: 'Show one finger!',
  number_two: 'Show two fingers!',
  number_three: 'Show three fingers!',
  number_four: 'Show four fingers!',
  number_five: 'Show all five!',
  relaxed_spread: 'Relax and spread fingers gently!',
  half_fist: 'Light fist — not too tight!',
  index_only: 'Only index straight!',
  thumb_out: 'Thumb out to the side!',
  spread_wide: 'Spread fingers as wide as you can!',
  arm_raise: 'Raise your arm straight up overhead!',
  elbow_flex: 'Bend your elbow — bring hand to shoulder!',
  shoulder_abduct: 'Lift your arm out to the side!',
  wrist_circle: 'Rotate your wrist in slow circles!',
}

/** Voice cache keys — reuse 3 base clips where needed. */
export const VOICE_KEYS: Record<Gesture, string> = {
  open_hand: 'open_hand',
  fist: 'make_fist',
  point: 'point',
  thumbs_up: 'open_hand',
  peace_sign: 'open_hand',
  ok_sign: 'make_fist',
  pinch: 'make_fist',
  flat_hand: 'open_hand',
  shaka: 'open_hand',
  rock_on: 'open_hand',
  stop_hand: 'open_hand',
  claw: 'make_fist',
  pinch_wide: 'make_fist',
  tripod_grasp: 'make_fist',
  lateral_pinch: 'make_fist',
  number_one: 'point',
  number_two: 'open_hand',
  number_three: 'open_hand',
  number_four: 'open_hand',
  number_five: 'open_hand',
  relaxed_spread: 'open_hand',
  half_fist: 'make_fist',
  index_only: 'point',
  thumb_out: 'open_hand',
  spread_wide: 'open_hand',
  arm_raise: 'open_hand',
  elbow_flex: 'open_hand',
  shoulder_abduct: 'open_hand',
  wrist_circle: 'open_hand',
}
